(function(){
  const refs={landing:"/assets/reference-landing.jpg",work:"/assets/reference-work.jpg"};
  const projects={
    "lang-ong-ba-chieu":{title:"LĂNG ÔNG\nBÀ CHIỂU",eyebrow:"01 — BRANDING DESIGN",intro:"A contemporary identity inspired by the cultural layers, rituals and living memory surrounding Lăng Ông Bà Chiểu in Ho Chi Minh City.",blocks:[{type:"fullImage",src:"/assets/project-exotrails.jpg",alt:"Lăng Ông Bà Chiểu visual identity"},{type:"twoImages",images:[{src:refs.work,alt:"Project typography"},{src:refs.landing,alt:"Project applications"}]}]},
    vinamilk:{title:"VINAMILK",eyebrow:"02 — SOCIAL CREATIVE DESIGN",intro:"Social-first creative built around bold type, direct storytelling and a flexible visual system for digital communication.",blocks:[{type:"fullImage",src:"/assets/project-vinamilk.jpg",alt:"Vinamilk social creative"},{type:"twoImages",images:[{src:refs.landing,alt:"Campaign applications"},{src:refs.work,alt:"Campaign typography"}]}]},
    exotrails:{title:"EXOTRAILS",eyebrow:"03 — VIDEO & MOTION",intro:"A kinetic set of campaign visuals translating exploration, progress and outdoor community into energetic digital stories.",blocks:[{type:"fullImage",src:"/assets/project-exotrails.jpg",alt:"ExoTrails campaign"},{type:"twoImages",images:[{src:refs.landing,alt:"Motion frames"},{src:refs.work,alt:"Campaign system"}]}]},
    deye:{title:"DEYE",eyebrow:"02 — SOCIAL CREATIVE DESIGN",intro:"A modular social design system communicating energy technology with clarity while keeping every post visually engaging.",blocks:[{type:"fullImage",src:"/assets/project-deye.jpg",alt:"Deye social campaign"},{type:"twoImages",images:[{src:refs.landing,alt:"Deye campaign pieces"},{src:refs.work,alt:"Deye content system"}]}]},
    karrots:{title:"KARROTS",eyebrow:"04 — PHOTOGRAPHY / CREATIVE",intro:"A bright visual world where product photography and graphic elements meet in a playful, recognizable brand language.",blocks:[{type:"fullImage",src:"/assets/project-karrots.jpg",alt:"Karrots creative project"},{type:"twoImages",images:[{src:refs.landing,alt:"Karrots applications"},{src:refs.work,alt:"Karrots visual system"}]}]}
  };
  window.DASKOOL_PROJECTS=projects;
})();
